backend:
  name: github
  repo: seffw/hugo_test # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "content" # Used in routes, e.g. /admin/collections/blog
    label: "Content" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Middle Title", name: "middle_title", widget: "string"}
      - {label: "Middle Content", name: "middle_content", widget: "string"}
      - {label: "Right Title", name: "right_title", widget: "string"}
      - {label: "Right Content", name: "right_content", widget: "string"}
      - {label: "Button", name: "button", widget: "string"}
